name: Update Data
on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: false
          fetch-depth: 0
      - name: Update Submodules
        run: |
          git submodule init
          git submodule update --remote --force --depth 1
          git status
      - name: Use Node LTS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
      - name: Installing dependencies
        run: npm ci
      - name: Running translater
        run: npm start
      - name: Get date
        run: echo "TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_ENV"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          message: "cron: data update ${{ env.TIMESTAMP }}"
